USE [MuOnline]
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MEMB_INFO' AND COLUMN_NAME = 'GiftCount')
BEGIN
	ALTER TABLE MEMB_INFO ADD GiftCount [int] NOT NULL
	CONSTRAINT GiftCount_Default DEFAULT 0;
END
