--------------------------------
-- Query AutoSave JewelBank
--------------------------------
USE [MuOnline]
GO

IF NOT EXISTS(SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'XTR_JewelStore' AND COLUMN_NAME = 'AutoSave') 
ALTER TABLE XTR_JewelStore ADD [AutoSave] TINYINT DEFAULT 0 NOT NULL

IF NOT EXISTS(SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'XTR_JewelStore' AND COLUMN_NAME = 'AutoSaveResetTime') 
ALTER TABLE XTR_JewelStore ADD [AutoSaveResetTime] INT DEFAULT 0 NOT NULL

IF NOT EXISTS(SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'XTR_JewelStore' AND COLUMN_NAME = 'AutoSaveCount') 
ALTER TABLE XTR_JewelStore ADD [AutoSaveCount] INT DEFAULT 0 NOT NULL