USE [MuOnline]
GO

/****** Object:  Table [dbo].[XTR_PetInventory]    Script Date: 15/8/2021 08:47:40 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[XTR_PetInventory](
	[Name] [varchar](10) NOT NULL,
	[PetInventory] [varbinary](16) NULL,
 CONSTRAINT [PK_XTR_PetInventory] PRIMARY KEY CLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

